name: advent_of_code_2020

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build
        run: cargo +nightly build --all --release

      - name: Clean to prep for test coverage
        uses: actions-rs/cargo@v1
        with:
          command: clean

      - uses: actions-rs/tarpaulin@v0.1
        with:
          args: --all-features --coveralls ${{ secrets.GITHUB_TOKEN }}